---
title: "OleABCD hydrcarbons in the oceans"
output:
  flexdashboard::flex_dashboard:
  theme: cosmo
vertical_layout: fill
runtime: shiny
---
  
```{r setup, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
# getOption("repos")
# options(repos = BiocManager::repositories())
library(flexdashboard)
library(knitr)
library(shiny)
library(tidyverse)
library(plotly)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      message = FALSE, fig.align = 'center',
                      fig.dim = c(4, 6))
```


```{r global, include = FALSE, echo = FALSE, warning = TRUE}
# Read in the dataset for mapping
dat <- read_csv("../../data/TARA_tree_annotation_df.csv")
dat <- data.frame(dat) # This is a weird conversion required from a tibble to a data frame
```

Sample plot
=====================================
Inputs {.sidebar data-width=350}
----------------------------------------------------------------------

```{r}
selectInput(inputId = "color_env", 
            label = "Plot points by:", 
            choices = c("temperature", "oxygen", "depth_m"),
            selected = "temperature")
```

This world map shows the sampling locations of TARA Oceans MAGs that have OleA[B]CD genes colored by their features.

Please note the geographic coordinates have been randomly 'jittered' within 50 kilometers of the sampling location to limit the overlap of data points and  visually display all MAGs obtained from each site.

Column {.tabset}
----------------------------------------------------------------------
```{r }

renderPlotly({

fig1 <- plot_ly(dat, x = ~dat[[input$color_env]], color = ~polar, type = "box") %>%
  layout(yaxis = list(title = " "), xaxis = list(title = " "))

  # This is a great resource for all things R and plotly 
  # https://plotly.com/r/

  # Challenge 1. Repeat from yesterday: 
  # increase the number of variables available for plotting. 
  # beyond just oxygen, temperature, and depth_m

  # Challenge 2. Can you also create a 'selectInput' option for the boxplot y-axis 
  # (currently polar/nonpolar)?

  # Challenge 3. Add either another tab or panel to your flexdashboard with another 
  # plotly plot with a different type e.g. "scatter" or "bar"

  # Challenge 4. Change the hover text formatting to only display numbers to 1 decimal place
  # Hint: the function 'round' will be helpful
  # https://plotly.com/r/hover-text-and-formatting/

  # Challenge 5. Remove NAs so they don't mess-up your plots...
  # any thoughts on how to do this dynamically for each different input variable?
 
  # Challenge 6. Add a new tab/page with your leaflet map from yesterday

  # Challenge 7. Include psychrophile and thermophile data! 
  # Plot them both on the map and with plotly. 

  # Challenge 8.
  # Make an interative boxplot to look at the differences in 
  # temperature distribution for psychrophiles, thermophiles, and mesophiles
  
})
```


