---
title: "Comparison of oleA-containing bacteria"
output:
  flexdashboard::flex_dashboard:
  theme: cosmo
vertical_layout: fill
runtime: shiny
---
  
```{r setup, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
# getOption("repos")
# options(repos = BiocManager::repositories())
library(flexdashboard)
library(knitr)
library(shiny)
library(tidyverse)
library(plotly)
library(leaflet)
library(leaflet.providers)
library(scales)
library(gggenes)
library(ggtree)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      message = FALSE, fig.align = 'center',
                      fig.dim = c(4, 6))
```


```{r global, include = FALSE, echo = FALSE, warning = TRUE}
# Read in the dataset for mapping

dat <- read_csv("../../data/full50_1.csv")
dat <- data.frame(dat)

```

Scatter plot {data-icon="fa-hashtag"}
=====================================
Inputs {.sidebar data-width=350}
----------------------------------------------------------------------

```{r}
choicesvec <- dat %>% 
            select_if(is.numeric)

selectInput(inputId = "I1", 
            label = "Plot x-axis by:", 
            choices = colnames(choicesvec),
            selected = "depth_m")
selectInput(inputId = "I2", 
            label = "Plot y-axis by:", 
            choices = colnames(dat),
            selected = "temperature")
selectInput(inputId = "I3", 
            label = "Color points by:", 
            choices = colnames(dat),
            selected = "polar")
```

Column {.tabset}
----------------------------------------------------------------------
```{r }

renderPlotly({
fig1 <- plot_ly(dat, x = ~dat[,input$I1], y = ~dat[,input$I2], color = ~dat[,input$I3], type = "scatter") %>%
  layout(yaxis = list(title = " "), xaxis = list(title = " "))
  # add_trace()

})
```

Box plot {data-icon="fa-star"}
===============================================
Inputs {.sidebar data-width=350}
-------------------------------------------------------------------------------------
```{r}
selectInput(inputId = "I4", 
            label = "Plot x-axis by:", 
            choices = colnames(choicesvec),
            selected = "temperature")
selectInput(inputId = "I5", 
            label = "Plot y-axis by:", 
            choices = colnames(dat),
            selected = "temperature_range")

```

Output
-----------------------------------------------------------------------------------

```{r }

renderPlotly({

fig2 <- plot_ly(dat, x = ~dat[,input$I4], y = ~dat[,input$I5], type = "box") %>%
  layout(yaxis = list(title = " "), xaxis = list(title = " "))

})
```

Sampling Map {data-icon="fa-heart"}
=====================================
Inputs {.sidebar data-width=350}
----------------------------------------------------------------------

```{r}
choicesvec <- dat %>% 
            select_if(is.numeric)
selectInput(inputId = "I10", 
            label = "Color points by:", 
            choices = colnames(choicesvec),
            selected = "temperature")

selectInput(inputId = "I11", 
            label = "Change radius of points by:", 
            choices = colnames(choicesvec),
            selected = "depth_m")
```

This world map shows the sampling locations of TARA Oceans MAGs that have OleA[B]CD genes colored by their features.

Please note the geographic coordinates have been randomly 'jittered' within 50 kilometers of the sampling location to limit the overlap of data points and  visually display all MAGs obtained from each site.

Output
----------------------------------------------------------------------
```{r }

renderLeaflet({

  # Logic gates to check if input variable is numeric or not  
    
  # If input variable is numeric...
  if (is.numeric(dat[ ,colnames(dat) == input$I10])) {
      pal <- colorNumeric(
        palette = "RdYlBu",
        na.color = "gray70",
        reverse = TRUE,
        domain = dat[ ,colnames(dat) == input$I10])
    }


  # If input variable is not numeric then...
  if (!is.numeric(dat[ ,colnames(dat) == input$I10])) {

      # Convert to a factor
      dat[,colnames(dat) == input$I10] <- as.factor(dat[,colnames(dat) == input$I10])

      # Color by factor
      pal <- colorFactor(
        palette = "RdYlBu",
        na.color = "gray70",
        domain = dat[ ,colnames(dat) == input$I10])
  }
    
  content <- paste("Genus:", dat$genus, "<br>",
                    "Family:", dat$family, "<br>",
                   input$I10, ":", dat[,colnames(dat) == input$I10], "<br>",
                   input$I11, ":", dat[,colnames(dat) == input$I11])

  leaflet(data = dat) %>%
      addProviderTiles(providers$Esri.WorldPhysical) %>%
      addCircleMarkers(lng = ~lon, lat = ~lat,
        popup = content,
        radius = case_when(
          is.na(dat[,colnames(dat) == input$I11]) == FALSE
          ~ log(dat[,colnames(dat) == input$I11]) %>% 
                     scales::rescale(to = c(3, 7)),
          TRUE ~ 3),      
        fillOpacity = 0.5, 
        stroke = FALSE,
        color = ~pal(dat[ ,colnames(dat) == input$I10]))
})
```


Gene Diagram {data-icon="fa-square"}
=====================================
Inputs {.sidebar data-width=350}
----------------------------------------------------------------------


Output
----------------------------------------------------------------------
```{r }
ml <- read.tree("../../data/trees/20200617_20_psychro_thermo_ML_500boot.nwk")
mlt <- ggtree(ml)


mlt$data <- mlt$data %>% 
  mutate(genus = word(label, sep = "_", 2))

mlt$data$genus[grep("peg.1837", mlt$data$label)] <- "Deltaproteobacteria1"
mlt$data$genus[grep("peg.848", mlt$data$label)] <- "Deltaproteobacteria2"

mlt_dat1 <- read_csv("../../data/mlt_dat1.csv")
plotdat_fixed <- read_csv("../../data/plotdat_fixed.csv")

mltr2 <- mlt + 
  geom_tiplab(aes(label = mlt_dat1$genus), color = mlt_dat1$temp_color[1:20]) + 
  xlim_tree(5.8) + 
  geom_nodelab(aes(label = mlt_dat1$label2), hjust = 1.2, vjust = -0.25) +
  geom_facet(mapping = aes(xmin = start, xmax = end, fill = gene),
             data = plotdat_fixed, geom = geom_motif, panel = 'Alignment',
             on = "oleA") +
  scale_fill_brewer(palette = "Set3") + 
  scale_x_continuous(expand=c(0,0)) +
  theme(strip.text=element_blank(),
        panel.spacing=unit(0, 'cm'))

mltr3 <- mltr2 + facet_grid(cols = vars(factor(.panel, 
                    levels = c("Tree", "Alignment"))),
                    scales = 'free_x')

mltr3

```
