---
title: "Comparison of oleA-containing bacteria"
output:
  flexdashboard::flex_dashboard:
  theme: cosmo
vertical_layout: fill
runtime: shiny
---
  
```{r setup, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
# getOption("repos")
# options(repos = BiocManager::repositories())
library(flexdashboard)
library(knitr)
library(shiny)
library(tidyverse)
library(plotly)
library(leaflet)
library(leaflet.providers)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      message = FALSE, fig.align = 'center',
                      fig.dim = c(4, 6))
```


```{r global, include = FALSE, echo = FALSE, warning = TRUE}
# Read in the dataset for mapping
dat <- read_csv("../../data/full50_raw") # read_csv("../../data/TARA_tree_annotation_df.csv")
dat <- data.frame(dat) # This is a weird conversion required from a tibble to a data frame
 # full50 <- read_csv("../../data/full50_raw")
 # full50 <- data.frame(full50)

## to do list:
# any way to make input for full TARA set or 50 ordered?
# make radius input work for map
# challenges 4, 5, 7, 8
# fix jitters for new data
```

Scatter plot {data-icon="fa-hashtag"}
=====================================
Inputs {.sidebar data-width=350}
----------------------------------------------------------------------

```{r}
choicesvec <- dat %>% 
            select_if(is.numeric)
 # selectInput(inputId = "I0", 
 #            label = "Dataset:", 
 #           choices = #c("50 sequences")
 #           c("Full Dataset" = "../../data/TARA_tree_annotation_df.csv") 
 # )
selectInput(inputId = "I1", 
            label = "Plot x-axis by:", 
            choices = colnames(choicesvec),
            selected = "temperature")
selectInput(inputId = "I2", 
            label = "Plot y-axis by:", 
            choices = colnames(dat),
            selected = "depth_m")
selectInput(inputId = "I3", 
            label = "Color points by:", 
            choices = colnames(dat),
            selected = "polar")
```

Column {.tabset}
----------------------------------------------------------------------
```{r }

renderPlotly({
 # dat2 <- read_csv(input$I0)
fig1 <- plot_ly(dat, x = ~dat[,input$I1], y = ~dat[,input$I2], color = ~dat[,input$I3], type = "scatter") %>%
  layout(yaxis = list(title = " "), xaxis = list(title = " "))
  # add_trace()

  # This is a great resource for all things R and plotly 
  # https://plotly.com/r/

  # Challenge 1. Repeat from yesterday: 
  # increase the number of variables available for plotting. 
  # beyond just oxygen, temperature, and depth_m

  # Challenge 2. Can you also create a 'selectInput' option for the boxplot y-axis 
  # (currently polar/nonpolar)?

  # Challenge 3. Add either another tab or panel to your flexdashboard with another 
  # plotly plot with a different type e.g. "scatter" or "bar"

  ###### Challenge 4. Change the hover text formatting to only display numbers to 1 decimal place
  # Hint: the function 'round' will be helpful
  # https://plotly.com/r/hover-text-and-formatting/

  ######### Challenge 5. Remove NAs so they don't mess-up your plots...
  # any thoughts on how to do this dynamically for each different input variable?
 
  # Challenge 6. Add a new tab/page with your leaflet map from yesterday

  # Challenge 7. Include psychrophile and thermophile data! 
  # Plot them both on the map and with plotly. 

  # Challenge 8.
  # Make an interactive boxplot to look at the differences in 
  # temperature distribution for psychrophiles, thermophiles, and mesophiles
  
})
```

Box plot {data-icon="fa-star"}
===============================================
Inputs {.sidebar data-width=350}
-------------------------------------------------------------------------------------
```{r}
selectInput(inputId = "I4", 
            label = "Plot x-axis by:", 
            choices = colnames(choicesvec),
            selected = "temperature")
selectInput(inputId = "I5", 
            label = "Plot y-axis by:", 
            choices = colnames(dat),
            selected = "temperature_range")

```

Output
-----------------------------------------------------------------------------------

```{r }

renderPlotly({

fig2 <- plot_ly(dat, x = ~dat[,input$I4], y = ~dat[,input$I5], type = "box") %>%
  layout(yaxis = list(title = " "), xaxis = list(title = " "))

})
```

Sampling Map {data-icon="fa-heart"}
=====================================
Inputs {.sidebar data-width=350}
----------------------------------------------------------------------

```{r}
choicesvec <- dat %>% 
            select_if(is.numeric)
selectInput(inputId = "I10", 
            label = "Color points by:", 
            choices = colnames(choicesvec),
            selected = "temperature")

selectInput(inputId = "I11", 
            label = "Change radius of points by:", 
            choices = colnames(choicesvec),
            selected = "depth_m")
```

This world map shows the sampling locations of TARA Oceans MAGs that have OleA[B]CD genes colored by their features.

Please note the geographic coordinates have been randomly 'jittered' within 50 kilometers of the sampling location to limit the overlap of data points and  visually display all MAGs obtained from each site.

Output
----------------------------------------------------------------------
```{r }

renderLeaflet({

  # Logic gates to check if input variable is numeric or not  
    
  # If input variable is numeric...
  if (is.numeric(dat[ ,colnames(dat) == input$I10])) {
      pal <- colorNumeric(
        palette = "RdYlBu",
        na.color = "gray70",
        reverse = TRUE,
        domain = dat[ ,colnames(dat) == input$I10])
    }


  # If input variable is not numeric then...
  if (!is.numeric(dat[ ,colnames(dat) == input$I10])) {

      # Convert to a factor
      dat[,colnames(dat) == input$I10] <- as.factor(dat[,colnames(dat) == input$I10])

      # Color by factor
      pal <- colorFactor(
        palette = "RdYlBu",
        na.color = "gray70",
        domain = dat[ ,colnames(dat) == input$I10])
  }
  
# #  new <- dat %>% 
#     # make new column from the input so we can use that column from here on instead
#     
#  #   mutate(rad = case_when((log(depth_m) < 3) ~ 3,
#                            (log(depth_m) > 7) ~ 7,
#                          !is.na(depth_m) ~ log(depth_m),
#                          TRUE ~ 3)) 
    
  content <- paste("Genus:", dat$genus, "<br>",
                    "Family:", dat$family, "<br>",
                   input$I10, ":", dat[,colnames(dat) == input$I10], "<br>",
                   input$I11, ":", dat[,colnames(dat) == input$I11])

  leaflet(data = dat) %>%
      addProviderTiles(providers$Esri.WorldPhysical) %>%
      addCircleMarkers(lng = ~lon, lat = ~lat,
        popup = content,
        radius = log(dat[,colnames(dat) == input$I11]),      
        fillOpacity = 0.5, 
        stroke = FALSE,
        color = ~pal(dat[ ,colnames(dat) == input$I10]))
})
```
